### ISSUE TITLE
Various Bugs

### ISSUE THREAD

**Issue by flul6175** [Unamed001/x86webEmulator#20]
;Formatierfehler für Register AH, BH, CH, DH: wird als Hexadezimal erkannt;
;Sprunglabel im Format thisIsALabel wird nicht gefunden (vermutlich in Kleinbuchstaben konvertiert, aber normal gelesen)
;Zahl 0H - 9H nicht möglich
;JNC funktioniert nicht, wenn beide Register 0 sind (CF wird aber korrekt nicht gesetzt)

**Comment by Unamed001** [comment]
Syntax Highlighter Bug: Literals "H/h" "B/b" marked as numbers (should be labels). Found in 3f51ca1.

**Comment by Unamed001** [comment]
Done cd9e25a
